// packages/vue/src/components/DataDen.vue
<script setup lang="ts">
import {
  DataDen,
  DataDenOptions,
  // @ts-ignore
} from "../../../core/dist/js/data-den.es.min";
import { onMounted, ref } from "vue";

let dataDen: DataDen | null = null;
const dataDenWrapper = ref<HTMLDivElement | null>(null);

const props = defineProps<{
  options: DataDenOptions;
}>();

const emit = defineEmits(["sorting-done"]);

onMounted(() => {
  if (dataDenWrapper.value) {
    dataDen = new DataDen(dataDenWrapper.value, props.options);
    // @ts-ignore
    dataDenWrapper.value.addEventListener(
      "info:sorting:done",
      (event: CustomEvent) => {
        emit("sorting-done", event);
      }
    );
  }
});

const sort = (field: string, order: string) => {
  if (dataDen) {
    dataDen.sort(field, order);
  }
};

defineExpose({
  sort,
});
</script>

<template>
  <div ref="dataDenWrapper"></div>
</template>

// packages/react/src/components/DataDen.tsx
import { useRef, forwardRef, useEffect, useImperativeHandle } from "react";
import {
  DataDen as DataDenCore,
  DataDenOptions,
  // @ts-ignore
} from "../../../core/dist/js/data-den.es.min";

const DataDen = forwardRef(function DataDen(
  {
    options,
    onSortingDone,
  }: {
    options: DataDenOptions;
    onSortingDone: (event: CustomEvent) => void;
  },
  ref: any
) {
  let dataDen: DataDenCore | null = null;
  const dataDenWrapper = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!dataDen && dataDenWrapper.current) {
      dataDen = new DataDenCore(dataDenWrapper.current, options);

      // @ts-ignore
      dataDenWrapper.current.addEventListener(
        "info:sorting:done",
        (event: CustomEvent) => {
          onSortingDone(event);
        }
      );
    }
  }, [dataDenWrapper]);

  useImperativeHandle(ref, () => ({
    sort(field: string, order: string) {
      if (dataDen) {
        dataDen.sort(field, order);
      }
    },
  }));

  return <div ref={dataDenWrapper}></div>;
});

export default DataDen;
